version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - my-network

  server:
    build:
      context: ./server
    ports:
      - "9000:9000"
    networks:
      - my-network

networks:
  my-network:
